#!/usr/bin/env python

import sys
import zmq

if len(sys.argv) < 3:
    print "Usage: %s <port> <txid>" % sys.argv[0]
    sys.exit(1)

port = int(sys.argv[1])

context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect("tcp://127.0.0.1:%s" % port)

socket.send(sys.argv[2])
socket.recv()   # for completeness' sake
